---
- name: Restart SigNoz stack
  command: docker compose restart
  args:
    chdir: /opt/signoz
  become: true
  become_user: "{{ ops_user }}"

- name: Stop SigNoz stack
  command: docker compose down
  args:
    chdir: /opt/signoz
  become: true
  become_user: "{{ ops_user }}"

- name: Start SigNoz stack
  command: docker compose up -d
  args:
    chdir: /opt/signoz
  become: true
  become_user: "{{ ops_user }}"
