// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: sample-app/order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessOrderRequest) Reset() {
	*x = ProcessOrderRequest{}
	mi := &file_sample_app_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessOrderRequest) ProtoMessage() {}

func (x *ProcessOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sample_app_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessOrderRequest.ProtoReflect.Descriptor instead.
func (*ProcessOrderRequest) Descriptor() ([]byte, []int) {
	return file_sample_app_order_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ProcessOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Duration      string                 `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessOrderResponse) Reset() {
	*x = ProcessOrderResponse{}
	mi := &file_sample_app_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessOrderResponse) ProtoMessage() {}

func (x *ProcessOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sample_app_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessOrderResponse.ProtoReflect.Descriptor instead.
func (*ProcessOrderResponse) Descriptor() ([]byte, []int) {
	return file_sample_app_order_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ProcessOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProcessOrderResponse) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

var File_sample_app_order_proto protoreflect.FileDescriptor

const file_sample_app_order_proto_rawDesc = "" +
	"\n" +
	"\x16sample-app/order.proto\x12\x05order\"0\n" +
	"\x13ProcessOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\x7f\n" +
	"\x14ProcessOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\tR\bduration2W\n" +
	"\fOrderService\x12G\n" +
	"\fProcessOrder\x12\x1a.order.ProcessOrderRequest\x1a\x1b.order.ProcessOrderResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_sample_app_order_proto_rawDescOnce sync.Once
	file_sample_app_order_proto_rawDescData []byte
)

func file_sample_app_order_proto_rawDescGZIP() []byte {
	file_sample_app_order_proto_rawDescOnce.Do(func() {
		file_sample_app_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sample_app_order_proto_rawDesc), len(file_sample_app_order_proto_rawDesc)))
	})
	return file_sample_app_order_proto_rawDescData
}

var file_sample_app_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sample_app_order_proto_goTypes = []any{
	(*ProcessOrderRequest)(nil),  // 0: order.ProcessOrderRequest
	(*ProcessOrderResponse)(nil), // 1: order.ProcessOrderResponse
}
var file_sample_app_order_proto_depIdxs = []int32{
	0, // 0: order.OrderService.ProcessOrder:input_type -> order.ProcessOrderRequest
	1, // 1: order.OrderService.ProcessOrder:output_type -> order.ProcessOrderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sample_app_order_proto_init() }
func file_sample_app_order_proto_init() {
	if File_sample_app_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sample_app_order_proto_rawDesc), len(file_sample_app_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sample_app_order_proto_goTypes,
		DependencyIndexes: file_sample_app_order_proto_depIdxs,
		MessageInfos:      file_sample_app_order_proto_msgTypes,
	}.Build()
	File_sample_app_order_proto = out.File
	file_sample_app_order_proto_goTypes = nil
	file_sample_app_order_proto_depIdxs = nil
}
